// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMTyrDdTND0ydGUgUiFiXS0k3FU5ZfQqw',
    appId: '1:179488083210:web:08cf4c34b071c7f7b87ef3',
    messagingSenderId: '179488083210',
    projectId: 'guxi-shop',
    authDomain: 'guxi-shop.firebaseapp.com',
    databaseURL: 'https://guxi-shop-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'guxi-shop.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3NVb2Wc_4lKKV86Aoju7sAuVV1-MT2ys',
    appId: '1:179488083210:android:ff8e9577b317f215b87ef3',
    messagingSenderId: '179488083210',
    projectId: 'guxi-shop',
    databaseURL: 'https://guxi-shop-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'guxi-shop.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZFSzP_db1ejtVqrTwedDBt4ybrdEKeZQ',
    appId: '1:179488083210:ios:2c8de37e936ec2aeb87ef3',
    messagingSenderId: '179488083210',
    projectId: 'guxi-shop',
    databaseURL: 'https://guxi-shop-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'guxi-shop.firebasestorage.app',
    iosBundleId: 'com.example.shopGucci',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZFSzP_db1ejtVqrTwedDBt4ybrdEKeZQ',
    appId: '1:179488083210:ios:2c8de37e936ec2aeb87ef3',
    messagingSenderId: '179488083210',
    projectId: 'guxi-shop',
    databaseURL: 'https://guxi-shop-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'guxi-shop.firebasestorage.app',
    iosBundleId: 'com.example.shopGucci',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMTyrDdTND0ydGUgUiFiXS0k3FU5ZfQqw',
    appId: '1:179488083210:web:ab920036169feda8b87ef3',
    messagingSenderId: '179488083210',
    projectId: 'guxi-shop',
    authDomain: 'guxi-shop.firebaseapp.com',
    databaseURL: 'https://guxi-shop-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'guxi-shop.firebasestorage.app',
  );
}
